name: Run

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    container:
      image: johnramsden/upmem
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: true
      - name: Build DEBUG=1
        run: cd PIM_HDC && DEBUG=1 make
      - name: "DEBUG: Run on host"
        run: cd PIM_HDC && ./pim_hdc -i data/small-data.bin -s
      - name: "DEBUG: Run on DPU"
        run: cd PIM_HDC && ./pim_hdc -d -i data/small-data.bin -s
      - name: Build
        run: cd PIM_HDC && make clean && make
      - name: Run compare test
        run: cd PIM_HDC && ./pim_hdc -i data/small-data.bin -s -t
