name: Run

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    container:
      image: johnramsden/upmem
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: true
      - name: Build DEBUG=1
        run: cd PIM_HDC && DEBUG=1 make
      - name: "DEBUG: Run on host"
        run: cd PIM_HDC && ./pim_hdc
      - name: "DEBUG: Run on DPU"
        run: cd PIM_HDC && ./pim_hdc -d
      - name: Build
        run: cd PIM_HDC && make clean && make
      - name: Run on host
        run: cd PIM_HDC && ./pim_hdc | tee host.results.log
      - name: Run on DPU
        run: cd PIM_HDC && ./pim_hdc -d | tee dpu.results.log
      - name: Compare results
        run: cd PIM_HDC && [ -z "$(diff host.results.log dpu.results.log)" ] || exit 1
