name: Run

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    container:
      image: johnramsden/upmem
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: true
      - name: Build
        run: cd PIM_HDC && DEBUG=1 make
      - name: Run on host
        run: cd PIM_HDC && ./pim_hdc
      - name: Run on DPU
        run: cd PIM_HDC && ./pim_hdc -d
